version: "3.9"

services:

  pg:
    image: postgres
    restart: always
    container_name: pomodoro_postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${APP_CONFIG__DB__POSTGRES_DB}
      POSTGRES_USER: ${APP_CONFIG__DB__POSTGRES_USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data/

volumes:
  pg_volume: