"""change field name

Revision ID: ab638f89bfea
Revises: 1027f4f57d48
Create Date: 2024-12-11 14:31:47.773566

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab638f89bfea"
down_revision: Union[str, None] = "1027f4f57d48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("category", sa.Integer(), nullable=False))
    op.drop_constraint("fk_tasks_category_id_categorys", "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_tasks_category_categorys"),
        "tasks",
        "categorys",
        ["category"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("tasks", "category_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f("fk_tasks_category_categorys"), "tasks", type_="foreignkey")
    op.create_foreign_key(
        "fk_tasks_category_id_categorys",
        "tasks",
        "categorys",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("tasks", "category")
    # ### end Alembic commands ###
