"""add mixin and foreign key

Revision ID: 1027f4f57d48
Revises: 2abe492e2411
Create Date: 2024-12-10 17:43:51.985111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1027f4f57d48'
down_revision: Union[str, None] = '2abe492e2411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorys', sa.Column('created', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('categorys', sa.Column('updated', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('tasks', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('created', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('tasks', sa.Column('updated', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.create_foreign_key(op.f('fk_tasks_category_id_categorys'), 'tasks', 'categorys', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_category_id_categorys'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'updated')
    op.drop_column('tasks', 'created')
    op.drop_column('tasks', 'category_id')
    op.drop_column('categorys', 'updated')
    op.drop_column('categorys', 'created')
    # ### end Alembic commands ###
